### ISSUE TITLE
Should DseVector actually be an ordered CiteCollection...?

### ISSUE THREAD

**Issue by neelsmith** [cite-architecture/dse#13]

**Comment by Eumaeus** [comment]
No. The surfaces are ordered, and the passages are ordered.

Although we could consider adding a (sort by passage) and (sort by surface), assuming there is a Corpus with all the passages, and a Collection with all the surfaces.

**Comment by Eumaeus** [comment]
Actually, yes. We have them as ordered collections at the moment. That gives maximum flexibility. The surface-order, the text-order, _or_ the DSE record order. And if you have more than one text represented on a surface, and have an opinion about sequence, the DSE sequence can capture that.

**Comment by neelsmith** [comment]
closing.
